server:
  port: 8888

spring:
  profiles:
    active: native
  application:
    name: configuration-service
  cloud:
    config:
      server:
        boostrap: true
        native:
          search-location: classpath:/config